#!/usr/bin/env sh

usage() {
    cat <<EOT
Usage:
    pr-bisect bad_commit_id good_commit_id git_bisect_run_command
EOT
    exit 0
}

if [ "$#" -lt 3 ]; then
   usage
fi

bad_commit=$1
good_commit=$2
shift 2
git_bisect_command=$@

PATH=$pwd:$PATH
git bisect reset
find-broken-pr "${bad_commit}" "${good_commit}" "${git_bisect_command}"
find-broken-commit-in-pr "HEAD" "${git_bisect_command}"
git bisect reset
