name: publish

on: [push]

jobs:
  publish-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Install deps
      run: |
          wget https://github.com/casey/just/releases/download/0.10.1/just-0.10.1-x86_64-unknown-linux-musl.tar.gz
          tar -xvf just-0.10.1-x86_64-unknown-linux-musl.tar.gz
          ./just --version
          mkdir -p /home/runner/.local/bin/
          mv just /home/runner/.local/bin/

    - name: Build and Test
      run: |
        echo $PATH
        ls -all /home/runner/.local/bin/
        just --version
        just test

    - name: Push
      run: |
        just push
